FROM ubuntu:20.04 as base

# Actualizar y descargar paquetes 
RUN apt update && \
        DEBIAN_FRONTEND=noninteractive apt-get install -y \
        wireshark \
        vsftpd \ 
        apache2 \
        curl \
        openssh-server \
        iproute2 \
        php \
        php-cli \
        nano \
        vim \
        x11-utils \
        && rm -rf /var/lib/apt/lists/* 

# Exponer puerto 80 para apache y 22 para SSH
EXPOSE 80
EXPOSE 22
EXPOSE 21
EXPOSE 20

# Estartear el servicio de apache y SSH
CMD service ssh start && apache2ctl -D FOREGROUND

# Establece la variable de entoro DISPLAY para que apunte al servidor X del sistema
ENV DISPLAY=:0
