[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.websecure]
    address = ":443"
    [entryPoints.websecure.http.tls]
      certResolver = "myresolver"

[tls]
  [tls.certificates]
    certFile = "/certs/local.crt"
    keyFile = "/certs/local.key"
  [tls.options]
    [tls.options.mytls]
      minVersion = "VersionTLS12"

[providers]
  [providers.docker]
    exposedByDefault = false
  [providers.file]
    filename = "/etc/traefik/dynamic_conf/conf.yml"

[http]
  [http.routers]
    [http.routers.pino-php]
      rule = "Host(`pino-php.local`)"
      service = "pino-php"
      entryPoints = ["websecure"]
      [http.routers.pino-php.tls]
        options = "mytls"
    [http.routers.arbusto-php]
      rule = "Host(`arbusto-php.local`)"
      service = "arbusto-php"
      entryPoints = ["websecure"]
      [http.routers.arbusto-php.tls]
        options = "mytls"

  [http.services]
    [http.services.pino-php.loadBalancer]
      [[http.services.pino-php.loadBalancer.servers]]
        url = "http://pino-php:80"
    [http.services.arbusto-php.loadBalancer]
      [[http.services.arbusto-php.loadBalancer.servers]]
        url = "http://arbusto-php:80"
