FROM ubuntu:latest

# Actualizar y descargar paquetes 
RUN apt update && \
        DEBIAN_FRONTEND=noninteractive apt-get install -y \
        wireshark \
        apache2 \
        curl \
        openssh-server \
        iproute2 \
        php \
        php-cli \
        php-fpm \
        nano \
        vim \
        x11-utils \
        && rm -rf /var/lib/apt/lists/* 

# Exponer puerto 80 y 5000 para el apache y 22 para el SSH
EXPOSE 80
EXPOSE 5000 
EXPOSE 22

# Estartear el servicio de apache y SSH
CMD service ssh start && apache2ctl -D FOREGROUND

# Establece la variable de entoro DISPLAY para que apunte al servidor X del sistema
ENV DISPLAY=:0