FROM ubuntu:latest

# Instalación de herramientas necesarias
RUN apt-get update && \
    apt-get install -y curl \
    nmap \
    unzip \
    iproute2 \
    net-tools \
    nano \
    vim \
    wireshark
